language: generic
services: docker

before_install:
  - wget http://director.downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2018-11-15/2018-11-13-raspbian-stretch-lite.zip
  - unzip 2018-11-13-raspbian-stretch-lite.zip

script:
  - docker-compose run pimod pimod.sh Base.Pifile
  - docker-compose run pimod pimod.sh Sensorbox.Pifile
  
deploy:
  provider: releases
  api_key:
    secure: DI9O67UCLBaVsyeQPle3yqogT05rkpPopeWYATbVbsQQnnijXQo4RC2n6LTk/EucpiJPQwqKCa03g4ml97G2O1qCugWfkMwer/OYxQlwFJAe16a7Xhc9MlwCK7lS4KwKlYRmJRkA5JBNB3IesKM37ArPEBIloj16qVuxG18u7gxhF0/tKXj0o/mgj282l+CQZPXwWXy/oKTgUOeHyLcFRHHCipKyH5v6xFE7MrNOIsJeKTk2B09pLzwTffr6n7rrwuaUmDs+EsApsmF1LbONdr3Q5VI/wX/+1RQeVVmAcoNjFD6oF+o9wAx1sAa8eLZFGPgdystCJSUSwqwW24j5QLsPTL9CkMWErzncxsQVm0PuRP3GJCNQquKH6t5wROG7RkjnDImBr9EB8gV4JTa4SnV877KZyMaWXvI9+ebN8pNMsiGuBkJA9G/il5+D0JTOIp3QVIcT6fZUv5+jx6HYgPs2qL8n+X0olLqbRfCXu+Wir+HEM9Q95RKPqso0LvFJ9RjqGIIBSeMAey6kq+WoRkDyZ+32Q9ICm+N1inmiZg9Nu9TaOp1EXTvh2EJYNPJ38UTm3sacq7t1O3TWwEvVT+2QHL5AGFEvoNXOWbwq/ZXY0SNO+YAioOX8Se36qoz9KqrF77Zj5rtNYR+fGpV3MeboD9RJ23+BLeobAzTnbIc=
  file:
    - Sensorbox.img
  on:
    tags: true
    repo: nature40/Sensorboxes
  overwrite: true
  prerelease: true
