version: '3'
services:
  pimod:
    build: ./pimod
    privileged: true
    tty: true
    volumes:
      - .:/BatRackOS
      - ./pimod:/pimod
    working_dir: /BatRackOS
    environment:
      - PATH:'$PATH:/pimod'
      - IMG
