version: '3'
services:
    pimod:
        build: ./pimod
        privileged: true
        volumes:
            - .:/sensorboxes
        working_dir: /sensorboxes
        environment:
            - PATH:'$PATH:/pimod'