name: Build Images

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Base Pifile
        uses: Nature40/pimod@v0.2.1
        with:
          pifile: Base.Pifile
      - name: Run Radiotracking Pifile
        uses: Nature40/pimod@v0.2.1
        with:
          pifile: RadioTracking.Pifile

      - name: Package RadioTracking.zip
        run: zip RadioTracking.zip RadioTracking.img
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
      - name: Upload RadioTracking.zip to release
        id: upload_radiotracking_zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: RadioTracking.zip
          asset_name: RadioTracking.zip
          asset_content_type: application/zip
