name: Build Images

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: recursive
          token: ${{ secrets.PAT_JONASHOECHST }}

      - name: Run Base Pifile
        uses: Nature40/pimod@v0.2.1
        with:
          pifile: Base.Pifile
      - name: Run BatRack Pifile
        uses: Nature40/pimod@v0.2.1
        with:
          pifile: BatRack.Pifile

      - name: Set Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Rename BatRack Image
        run: mv BatRack.img BatRack-${{ env.RELEASE_VERSION }}.img
      - name: Package BatRack.zip
        run: zip BatRack-${{ env.RELEASE_VERSION }}.zip BatRack-${{ env.RELEASE_VERSION }}.img
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
      - name: Upload BatRack.zip to release
        id: upload_batrack_zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: BatRack-${{ env.RELEASE_VERSION }}.zip
          asset_name: BatRack-${{ env.RELEASE_VERSION }}.zip
          asset_content_type: application/zip
